# name elasticsearch_kuromoji
FROM dockerfile/elasticsearch
# MAINTANER iwag


# Install 
# 2.2.0 for ES 1.2
# see https://github.com/elasticsearch/elasticsearch-analysis-kuromoji/
RUN /elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-kuromoji/2.2.0


#EXPOSE 9200
#EXPOSE 9300

