# docker-compose run web rails new . --force --database=postgresql
# docker-compose run web rake db:create

version: '3'
services:
  db:
    image: postgres
    envronment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
